# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nubemox-db
    environment:
      POSTGRES_USER: nubemox_user
      POSTGRES_PASSWORD: nubemox_password
      POSTGRES_DB: nubemox_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  # --- NOVO: SERVIDOR LDAP ---
  openldap:
    image: osixia/openldap:1.5.0
    container_name: nubemox-ldap
    command: --copy-service
    environment:
      LDAP_ORGANISATION: "Nubemox Corp"
      LDAP_DOMAIN: "nubemox.local"
      LDAP_ADMIN_PASSWORD: "admin"
      # Configura para carregar arquivos .ldif na inicialização
      LDAP_CONFIG_PASSWORD: "config"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      # Mapeia nossa pasta local de seeds para o container
      - ./ldap_seed:/container/service/slapd/assets/config/bootstrap/ldif/custom

  # --- NOVO: GUI PARA VER O LDAP ---
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: nubemox-ldap-ui
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap

volumes:
  postgres_data: